# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:03
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Base Account', max_length=128, null=True)),
                ('status', models.CharField(default='Open', max_length=32)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('is_source_account', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='is_source_account',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='is_source_account',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='status',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='id',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='is_source_account',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='name',
        ),
        migrations.RemoveField(
            model_name='systemaccount',
            name='status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investment_accounts.Account'),
        ),
        migrations.AddField(
            model_name='fundaccount',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default='Account', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investment_accounts.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default='Account', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investment_accounts.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemaccount',
            name='account_ptr',
            field=models.OneToOneField(auto_created=True, default='Account', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investment_accounts.Account'),
            preserve_default=False,
        ),
    ]
