# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 02:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0002_auto_20160408_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentaccount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investmentaccounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
