# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 19:37
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_system_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment_accounts', '0004_auto_20160409_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=64)),
                ('trial_period', models.PositiveIntegerField(blank=True, null=True)),
                ('trial_unit', models.CharField(choices=[(b'0', 'No trial'), (b'D', 'Day'), (b'W', 'Week'), (b'M', 'Month'), (b'S', 'Season'), (b'Y', 'Year')], max_length=1, null=True)),
                ('recurrence_period', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence_unit', models.CharField(choices=[(None, 'No recurrence'), (b'0', 'No trial'), (b'D', 'Day'), (b'W', 'Week'), (b'M', 'Month'), (b'S', 'Season'), (b'Y', 'Year')], max_length=1, null=True)),
                ('system', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='systems.System')),
            ],
            options={
                'ordering': ('price', '-recurrence_period'),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateField(default=datetime.datetime(2016, 4, 13, 19, 37, 55, 926464), null=True)),
                ('active', models.BooleanField(default=True)),
                ('cancelled', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment_accounts.Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set([('user', 'subscription')]),
        ),
    ]
