# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0005_auto_20160413_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='recurrence_unit',
            field=models.CharField(choices=[(None, 'No recurrence'), ('0', 'No trial'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('S', 'Season'), ('Y', 'Year')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='trial_unit',
            field=models.CharField(choices=[('0', 'No trial'), ('D', 'Day'), ('W', 'Week'), ('M', 'Month'), ('S', 'Season'), ('Y', 'Year')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 16, 13, 35, 34, 468836), null=True),
        ),
    ]
