# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0005_auto_20160413_1937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundaccount',
            options={'permissions': (('view_fund_account', 'View Fund Account'),)},
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 19, 15, 54, 30, 312045), null=True),
        ),
    ]
