# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 04:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0006_auto_20160419_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='fund_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment_accounts.FundAccount'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[(b'SYSTEM', 'System'), (b'FUND', 'Fund')], default='SYSTEM', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='system',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.System'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 20, 4, 18, 53, 963014), null=True),
        ),
    ]
