# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 04:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_fund_isinvestible'),
        ('investment_accounts', '0007_auto_20160420_0419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='fund_account',
        ),
        migrations.AddField(
            model_name='subscription',
            name='fund',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds.Fund'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 20, 4, 28, 35, 383207), null=True),
        ),
    ]
