# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0007_auto_20160416_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 17, 5, 26, 32, 226375), null=True),
        ),
    ]
