# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0008_auto_20160417_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(null=True),
        ),
    ]
