# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0010_auto_20160419_1025'),
        ('investment_accounts', '0008_auto_20160420_0428'),
    ]

    operations = [
    ]
