# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 05:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 23, 5, 16, 32, 666568), null=True),
        ),
    ]
