# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 05:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0012_auto_20160423_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='funds.Fund'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.System'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(default=datetime.datetime(2016, 4, 23, 5, 18, 17, 320579), null=True),
        ),
    ]
