# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_accounts', '0013_auto_20160423_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('SYSTEM', 'System'), ('FUND', 'Fund')], max_length=128),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='expires',
            field=models.DateField(null=True),
        ),
    ]
