# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecourse',
            name='racecoursecode',
            field=models.CharField(default='', max_length=35),
        ),
    ]
