# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_racecourse_racecoursecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='racecourse',
            name='straight',
            field=models.IntegerField(null=True),
        ),
    ]
