# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_racecourse_straight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bookmaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmakerbet', to='bets.Bookmaker'),
        ),
    ]
