# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_bet_bookmaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='oddsacheived',
            new_name='avgodds',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='istoWin',
            new_name='isWinMarket',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='betamount',
            new_name='stake',
        ),
        migrations.AddField(
            model_name='bet',
            name='isBack',
            field=models.BooleanField(default=True),
        ),
    ]
