# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-09 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0005_auto_20160409_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='didWin',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='winnings',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
