# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0007_auto_20160412_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racecourse',
            name='racecoursespeed',
            field=models.CharField(choices=[('GALLOPING', 'GALLOPING'), ('STIFF', 'STIFF'), ('TIGHT', 'TIGHT'), ('SHARP', 'SHARP')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='racecourse',
            name='racecoursesurface',
            field=models.CharField(choices=[('GALLOPING', 'GALLOPING'), ('STIFF', 'STIFF'), ('TIGHT', 'TIGHT'), ('SHARP', 'SHARP')], max_length=35, null=True),
        ),
    ]
