# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0008_auto_20160416_1335'),
        ('bets', '0008_auto_20160419_1554'),
    ]

    operations = [
    ]
