# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'get_latest_by': 'racedatetime', 'ordering': ['-racedatetime', 'system']},
        ),
        migrations.AlterIndexTogether(
            name='bet',
            index_together=set([('system', 'horsename', 'bookmaker')]),
        ),
    ]
