# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0009_merge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'get_latest_by': 'racedatetime', 'ordering': ['-racedatetime', 'system']},
        ),
        migrations.AlterField(
            model_name='bet',
            name='didWin',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='bet',
            name='finalpos',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='isPlaced',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='bet',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bet',
            name='winnings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterIndexTogether(
            name='bet',
            index_together=set([('system', 'horsename', 'bookmaker')]),
        ),
    ]
