# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0010_auto_20160423_0516'),
        ('bets', '0010_auto_20160423_0753'),
    ]

    operations = [
    ]
