# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0011_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='racedatetime',
            field=models.DateTimeField(db_index=True, help_text='race date time - LOCAL!'),
        ),
        migrations.AlterField(
            model_name='racecourse',
            name='racecoursename',
            field=models.CharField(db_index=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racedate',
            field=models.DateField(db_index=True, help_text='race date'),
        ),
    ]
