# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0012_auto_20160425_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='rprunner',
            name='racecoursename',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='l1distancechange',
            field=models.FloatField(null=True),
        ),
    ]
