# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 12:23
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='Investor', max_length=25, verbose_name='nickname')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en-us', 'English'), ('zh-cn', '简体中文'), ('zh-tw', '繁體中文'), ('de-de', 'Deutsch')], default='en-us', max_length=10, verbose_name='preferred language')),
                ('GBPbalance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('AUDbalance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('AUD', 'AUD'), ('GBP', 'GBP')], max_length=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('investor_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_from', to='investors.Investor')),
                ('investor_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_to', to='investors.Investor')),
            ],
        ),
    ]
