# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund',
            options={'get_latest_by': 'wentLive', 'ordering': ['-totalwinnings'], 'permissions': (('view_fund', 'View fund'),)},
        ),
    ]
