# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_auto_20160408_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='isInvestible',
            field=models.BooleanField(default=True),
        ),
    ]
