"""
Django settings for investment project.

Generated by 'django-admin startproject' using Django 1.9.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import re
import socket


env = os.environ.copy()
# export DJANGO_SETTINGS_MODULE=mi.investment.settings TRTING TO GET django-admin to work
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "investment.settings")
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CURRENCY_AUD = 'AUD'
CURRENCY_GBP = 'GBP'

CURRENCIES = ( (CURRENCY_AUD, 'AUD'), (CURRENCY_GBP, 'GBP'), )

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!1mhk49#$6#n(vp(8=464a%)!-f3w$ph8ahd4!cg^h4!lj)_h7'

# SECURITY WARNING: don't run with debug turned on in production!
if socket.gethostname() == 'metainvest':
    DEBUG = False
    ALLOWED_HOSTS = ['139.59.249.64' , 'metainvest.io' ]
else:
    DEBUG = True
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'investors',
    'guardian',
    'investment_accounts',
    'systems',
    'funds',
    'bets',
    'rp',
    'django.contrib.humanize',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django_tables2',
    'debug_toolbar'
]
#remove investments

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
]

ROOT_URLCONF = 'investment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.request',

            ],
        },
    },
]

WSGI_APPLICATION = 'investment.wsgi.application'




# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

#local
if DEBUG == True:
    DATABASES = {
       'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'lucky10',
            'USER': 'vmac',
            'PASSWORD': '',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }
else:
    #remote
    DATABASES = {
       'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'lucky10',
            'USER': 'devdb',
            'PASSWORD': '1devdb6',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    # 'allauth.account.auth_backends.AuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

if not DEBUG:
    STATIC_ROOT  = '/mi/sites/metainvest.io/htdocs/static/'



ROOT_DIR =  os.path.abspath(os.path.dirname(__file__))

STATICFILES_DIRS =  [os.path.join(ROOT_DIR, 'static/'), ]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

MEDIA_URL = '/media/'

LOGIN_REDIRECT_URL = '/'

SESSION_COOKIE_AGE = 2592000 # One month

SITE_ID = 1

#debug toolbar needs this
INTERNAL_IPS = '127.0.0.1'


DISALLOWED_USER_AGENTS = (
    re.compile(r'^OmniExplorer_Bot'),
    re.compile(r'^Googlebot'),
    )


ANONYMOUS_USER_NAME = 'Tester1'
