# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rprunner',
            old_name='isplaced',
            new_name='isPlaced',
        ),
    ]
