# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0002_auto_20160511_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rprunner',
            name='isScratched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='l1racedistancerange',
            field=models.CharField(choices=[('SPRINT', 'SPRINT'), ('MIDDLE', 'MIDDLE'), ('LONG', 'LONG')], max_length=35, null=True),
        ),
    ]
