# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_system_runners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'created', 'ordering': ('-levelbsprofitpc',)},
        ),
    ]
