# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20160404_0734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'default_permissions': (('view_system', 'View system'),), 'ordering': ('snapshotid',)},
        ),
        migrations.AlterField(
            model_name='runner',
            name='damname',
            field=models.CharField(help_text="Dam's name", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damsirename',
            field=models.CharField(help_text="Dam's sire name", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='isplaced',
            field=models.NullBooleanField(help_text='Placed?'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetime',
            field=models.CharField(help_text='Race off time', max_length=250, null=True),
        ),
    ]
