# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20160404_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='ages',
            field=models.CharField(help_text='entry type ages', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='allowance',
            field=models.SmallIntegerField(help_text='jockey allowance', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='distance',
            field=models.FloatField(help_text='distance furlongs', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='draw',
            field=models.SmallIntegerField(help_text='barrier', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fsraceno',
            field=models.CharField(help_text='distance', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fsrating',
            field=models.FloatField(help_text='FS Rating', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fsratingrank',
            field=models.SmallIntegerField(help_text='FS Rating rank', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='going',
            field=models.CharField(help_text='going', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='jockeyname',
            field=models.CharField(help_text='jockey', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='lbw',
            field=models.FloatField(help_text='Beaten by L', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='newraceclass',
            field=models.CharField(blank=True, help_text='new raceclass', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='oldraceclass',
            field=models.CharField(help_text='old raceclass', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racename',
            field=models.CharField(help_text='race name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetypeconditions',
            field=models.CharField(help_text='entry conditions', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetypehorse',
            field=models.CharField(help_text='entry type horse', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetypehs',
            field=models.CharField(help_text='handicap or stakes', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='sirename',
            field=models.CharField(help_text='sire name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='totalruns',
            field=models.SmallIntegerField(help_text='total runs horse', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='trainername',
            field=models.CharField(help_text='trainer', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='winsppos',
            field=models.SmallIntegerField(help_text='rank final starting price', null=True),
        ),
    ]
