# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 01:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_auto_20160407_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='rprunner',
            name='racecourseshape',
            field=models.CharField(choices=[('CIRCLE', 'CIRCLE'), ('HORSESHOE', 'HORSESHOE'), ('OVAL', 'OVAL'), ('PEAR', 'PEAR'), ('TRIANGLE', 'TRIANGLE')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='ages',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='bfpsp',
            field=models.DecimalField(decimal_places=2, help_text='Betfair SP place', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='bfsp',
            field=models.DecimalField(decimal_places=2, help_text='Betfair SP win', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='finalpos',
            field=models.CharField(help_text='Final position', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='isFROY',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='isbfplaced',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='isplaced',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='jockey_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='l1classchange',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'SOWN'), ('SAME', 'SAME')], max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='l1distancechange',
            field=models.CharField(choices=[('UP', 'UP'), ('DOWN', 'SOWN'), ('SAME', 'SAME')], max_length=135, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racecoursedirection',
            field=models.CharField(choices=[('STRAIGHT', 'STRAIGHT'), ('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racecoursegrade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racecourselocation',
            field=models.CharField(choices=[('SCOTLAND', 'SCOTLAND'), ('NORTH', 'NORTH'), ('MIDLANDS', 'MIDLANDS'), ('SOUTH', 'SOUTH'), ('IRE', 'IRE')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racecoursespeed',
            field=models.CharField(choices=[('GALLOPING', 'GALLOPING'), ('STIFF', 'STIFF'), ('TIGHT', 'TIGHT')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racecoursesurface',
            field=models.CharField(choices=[('GALLOPING', 'GALLOPING'), ('STIFF', 'STIFF'), ('TIGHT', 'TIGHT')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racedistancerange',
            field=models.CharField(choices=[('SPRINT', 'SPRINT'), ('MIDDLE', 'MIDDLE'), ('LONG', 'LONG')], max_length=35),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racemonth',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racetypeconditions',
            field=models.CharField(choices=[('CLAIMING', 'CLAIMING'), ('CLASSIFIED', 'CLASSIFIED'), ('CONDITIONS', 'CONDITIONS'), ('SELLING', 'SELLING'), ('ORDINARY', 'ORDINARY')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racetypehorse',
            field=models.CharField(choices=[('MAIDEN', 'MAIDEN'), ('NOVICE', 'NOVICE'), ('ORDINARY', 'ORDINARY')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='racetypehs',
            field=models.CharField(choices=[('H', 'HANDICAP'), ('S', 'STAKES')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='ridertype',
            field=models.CharField(choices=[('AMATEUR', 'AMATEUR'), ('APPRENTICE', 'APPRENTICE'), ('LADY', 'LADY'), ('ORDINARY', 'ORDINARY')], max_length=35),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='rpracegoing',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='trainer_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='winsp',
            field=models.FloatField(help_text='final starting price win', null=True),
        ),
        migrations.AlterField(
            model_name='rprunner',
            name='winsppos',
            field=models.SmallIntegerField(help_text='rank final starting price', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='runtype',
            field=models.CharField(choices=[('LIVE', 'LIVE'), ('HISTORICAL', 'HISTORICAL')], default='HISTORICAL', help_text='live_or_historical', max_length=20),
        ),
        migrations.AlterField(
            model_name='system',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='isActive',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='isLayPlace',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='isLayWin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='system',
            name='isTurf',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='system',
            name='oddsconditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
