# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20160404_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='damid',
            field=models.IntegerField(blank=True, default=None, help_text='Dam id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damsireid',
            field=models.IntegerField(blank=True, default=None, help_text='Dam sire id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='ownerid',
            field=models.IntegerField(blank=True, default=None, help_text='Owner id', null=True),
        ),
    ]
