# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20160408_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='validuptonotincluding',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 28, 0, 0)),
            preserve_default=False,
        ),
    ]
