# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_auto_20160404_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='horseid',
            field=models.IntegerField(blank=True, default=None, help_text='Horse id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='jockeyid',
            field=models.IntegerField(blank=True, default=None, help_text='Jockey id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='sireid',
            field=models.IntegerField(blank=True, default=None, help_text='Sire id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='trainerid',
            field=models.IntegerField(blank=True, default=None, help_text='Trainerid', null=True),
        ),
    ]
