# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 03:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_systemsnapshot_validuptonotincluding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='oddsconditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='rpquery',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='runners',
            field=models.ManyToManyField(default=[], to='systems.Runner'),
        ),
    ]
