# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_auto_20160408_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='runners',
            field=models.ManyToManyField(blank=True, to='systems.Runner'),
        ),
    ]
