# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_auto_20160408_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsnapshot',
            name='levelbspprofit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
