# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_auto_20160408_0709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RPRunner',
        ),
    ]
