# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_delete_rprunner'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='ownername',
            field=models.CharField(help_text="Owner's name", max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='racedatetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='rpgoing',
            field=models.CharField(help_text='going', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='runner',
            name='totalwins',
            field=models.FloatField(default=None, help_text='total wins horse', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='allowance',
            field=models.SmallIntegerField(default=0, help_text='jockey allowance'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damid',
            field=models.IntegerField(blank=True, default=None, help_text='Dam id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damname',
            field=models.CharField(help_text="Dam's name", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damsireid',
            field=models.IntegerField(blank=True, default=None, help_text='Dam sire id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='damsirename',
            field=models.CharField(help_text="Dam's sire name", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='draw',
            field=models.SmallIntegerField(help_text='barrier', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fsraceno',
            field=models.CharField(help_text='distance', max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fsrating',
            field=models.FloatField(help_text='FS Rating', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='fsratingrank',
            field=models.SmallIntegerField(help_text='FS Rating rank', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='isbfplaced',
            field=models.NullBooleanField(help_text='is Placed on Betfair?'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='isplaced',
            field=models.NullBooleanField(help_text='Placed?'),
        ),
        migrations.AlterField(
            model_name='runner',
            name='jockeyid',
            field=models.IntegerField(blank=True, default=None, help_text='Jockey id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='jockeyname',
            field=models.CharField(help_text='jockey', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='lbw',
            field=models.FloatField(help_text='Beaten by L', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='oldraceclass',
            field=models.CharField(help_text='old raceclass', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='ownerid',
            field=models.IntegerField(blank=True, default=None, help_text='Owner id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='sireid',
            field=models.IntegerField(blank=True, default=None, help_text='Sire id', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='sirename',
            field=models.CharField(help_text='sire name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='totalruns',
            field=models.SmallIntegerField(default=None, help_text='total runs horse', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='trainerid',
            field=models.IntegerField(blank=True, default=None, help_text='Trainerid', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='winsp',
            field=models.FloatField(help_text='final starting price win', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='winsppos',
            field=models.SmallIntegerField(help_text='rank final starting price', null=True),
        ),
    ]
