# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_auto_20160411_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='premium',
            field=models.FloatField(default=1.0),
        ),
    ]
