# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0012_system_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsnapshot',
            name='validfrom',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2001, 1, 1, 0, 0)),
        ),
    ]
