# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_auto_20160412_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='ages',
            field=models.CharField(help_text='entry type ages', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='distance',
            field=models.FloatField(help_text='distance furlongs', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='going',
            field=models.CharField(help_text='going', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racecourseid',
            field=models.IntegerField(blank=True, help_text='racecourseid', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racename',
            field=models.CharField(help_text='race name', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetypeconditions',
            field=models.CharField(help_text='entry conditions', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetypehorse',
            field=models.CharField(help_text='entry type horse', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='racetypehs',
            field=models.CharField(help_text='handicap or stakes', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='trainername',
            field=models.CharField(help_text='trainer', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='validfrom',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='systemsnapshot',
            unique_together=set([('system', 'validfrom', 'validuptonotincluding')]),
        ),
    ]
