# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_auto_20160412_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='allowance',
            field=models.SmallIntegerField(default=0, help_text='jockey allowance', null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='horseid',
            field=models.IntegerField(blank=True, default=None, help_text='Horse id', null=True),
        ),
    ]
