# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0016_auto_20160412_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='bfpsp',
            field=models.DecimalField(decimal_places=2, help_text='Betfair SP place', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='runner',
            name='bfsp',
            field=models.DecimalField(decimal_places=2, help_text='Betfair SP win', max_digits=6, null=True),
        ),
    ]
