# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0017_auto_20160412_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='runners',
            field=models.ManyToManyField(related_name='runners', to='systems.Runner'),
        ),
    ]
