# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0018_auto_20160416_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsnapshot',
            name='runners',
            field=models.ManyToManyField(related_name='snapshotrunners', to='systems.Runner'),
        ),
    ]
