# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0019_auto_20160416_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='runners',
            field=models.ManyToManyField(to='systems.Runner'),
        ),
    ]
