# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 05:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0020_auto_20160417_0802'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='systemsnapshot',
            managers=[
                ('yearobjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='system',
            name='isActive',
            field=models.BooleanField(verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='system',
            name='isLayPlace',
            field=models.BooleanField(default=False, verbose_name='PLACE LAY'),
        ),
        migrations.AlterField(
            model_name='system',
            name='isLayWin',
            field=models.BooleanField(default=False, verbose_name='LAY TO WIN'),
        ),
        migrations.AlterField(
            model_name='system',
            name='isTurf',
            field=models.BooleanField(verbose_name='is turf only'),
        ),
        migrations.AlterField(
            model_name='system',
            name='oddsconditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Odds must be'),
        ),
        migrations.AlterField(
            model_name='system',
            name='premium',
            field=models.FloatField(default=1.0, verbose_name='System price premium over base'),
        ),
        migrations.AlterField(
            model_name='system',
            name='systemname',
            field=models.CharField(max_length=50, unique=True, verbose_name='system name'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='a_e',
            field=models.FloatField(default=None, null=True, verbose_name='Actual vs. Expected wins'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='a_e_last50',
            field=models.FloatField(default=None, null=True, verbose_name='Actual vs. Expected, Last 50 Runs'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='archie_allruns',
            field=models.FloatField(default=None, null=True, verbose_name='Chi Squared All Runs'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='archie_last50',
            field=models.FloatField(default=None, null=True, verbose_name='Chi Squared Last 50 Runs'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='bfruns',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='No of Runs (BF)'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='bfwins',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='No of Wins (BF)'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='expectedwins',
            field=models.FloatField(default=None, null=True, verbose_name='Expected Wins'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='individualrunners',
            field=models.FloatField(default=None, null=True, verbose_name='No. Individual Runners'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='last28daysruns',
            field=models.SmallIntegerField(default=None, null=True, verbose_name='Last 28 Days Sumamry'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='last50str',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Last 50 Results'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='levelbspprofit',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='BF Profit at Level Stakes'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='runners',
            field=models.ManyToManyField(related_name='snapshotrunners', to='systems.Runner', verbose_name='Runners for this Snapshot'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systemsnapshots', to='systems.System'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='uniquewinners',
            field=models.FloatField(default=None, null=True, verbose_name='No. Unique Winners'),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='winsr',
            field=models.FloatField(default=None, null=True, verbose_name='WIN Strike Rate'),
        ),
    ]
