# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 02:05
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0021_auto_20160422_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='isActive',
            field=models.BooleanField(verbose_name='is currently in use'),
        ),
        migrations.AlterField(
            model_name='system',
            name='query',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
