# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0023_auto_20160423_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsnapshot',
            name='last28daysruns',
            field=models.CharField(default=None, max_length=250, null=True, verbose_name='Last 28 Days Summary'),
        ),
    ]
