# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0024_auto_20160423_0218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'created', 'ordering': ('-levelbspprofit',)},
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='levelbsprofitpc',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='runners',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='snapshottype',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='uniquewinnerstorunnerspc',
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='isHistorical',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='shortest_losing_streak',
            field=models.SmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='systemsnapshot',
            name='validfrom',
            field=models.DateTimeField(),
        ),
    ]
