# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0027_auto_20160423_0245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'validuptonotincluding', 'ordering': ('-levelbspprofit',)},
        ),
    ]
