# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 09:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0029_auto_20160423_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsnapshot',
            options={'default_permissions': ('view', 'add', 'change', 'delete'), 'get_latest_by': 'updated', 'ordering': ('-levelbspprofit',)},
        ),
        migrations.AlterModelManagers(
            name='systemsnapshot',
            managers=[
                ('thisyear', django.db.models.manager.Manager()),
            ],
        ),
    ]
