# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0030_auto_20160423_0937'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='systemsnapshot',
            managers=[
            ],
        ),
    ]
