# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0031_auto_20160423_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='systemname',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='system name'),
        ),
    ]
