# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 05:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0033_auto_20160425_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='shortest_losing_streak',
        ),
        migrations.RemoveField(
            model_name='systemsnapshot',
            name='stats',
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='l50_runseq',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='runseq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='season_archie',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='season_expected',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='season_runs',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='season_runseq',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='season_wins',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='season_winseq',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='top10_stakeplans',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='win_days',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='systemsnapshot',
            name='winseq',
            field=models.TextField(null=True),
        ),
    ]
