# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0034_auto_20160429_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewSystemRunners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('newrunner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.Runner')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.System')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='newrunners',
            field=models.ManyToManyField(related_name='newrunners', through='systems.NewSystemRunners', to='systems.Runner'),
        ),
    ]
