# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0035_auto_20160429_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='racecode',
            field=models.CharField(choices=[('A', 'AWT'), ('F', 'Flat'), ('J', 'Jumps')], default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='isToPlace',
            field=models.BooleanField(default=False),
        ),
    ]
